SITES=(
    rutracker.org
    pornolab.net
    kinozal.tv
    zencoder.ai
    plugins.jetbrains.com
    jetbrains.com
    download.jetbrains.com
    jetbra.in
    3.jetbra.in
    fe.zencoder.ai
    cdn.albionfreemarket.com
    api.albionfreemarket.com
    albionfreemarket.com
    europe.albion-online-data.com
    albiononline.com
    live.albiononline.com
    status.albiononline.com
    serverstatus.albiononline.com
    serverstatus-ams.albiononline.com
    serverstatus-sgp.albiononline.com
    forum.albiononline.com
)

SUBNETS=(
    52.85.49.0/24
    108.157.229.0/24
    18.66.102.0/24
    13.33.235.0/24
    3.171.214.0/24
)
